### ISSUE TITLE
Support baseline comparisons

### ISSUE THREAD

**Issue by rynowak** [aspnet/Stress#13]
Add the ability for a test to fail if the data is way out of sync with the baseline

**Comment by NTaylorMullen** [comment]
Infrastructure/implementation bits [here](https://github.com/aspnet/Stress/commit/32e60ee29a155107c47b4037ed19964c1bbd38ab). For now we just compare heap memory usage; however, I added infrastructure to add any number of additional comparison metrics. We should discuss what we want.
